### ISSUE TITLE
[Document] scantype=full 

### ISSUE THREAD

**Issue by davidkhala** [ServiceNow/sncicd-instance-scan#6]
Seeing below line, I wonder what is the meaing of specifying `full`. Does it mean an AND logic among all `[point, suite_combo, suite_scoped, suite_update]`?
> scantype - Type of scan process. Can be equal to full, point, suite_combo, suite_scoped, suite_update(Required).

**Comment by davidkhala** [comment]
The reason of asking so is from seeing an error in https://github.com/davidkhala/ci-cd-utils/runs/6658816513?check_suite_focus=true#step:3:9

**Comment by chiarng** [comment]
https://docs.servicenow.com/bundle/rome-servicenow-platform/page/administer/health-scan/task/hs-execute-full-scan.html
